# Site settings
title: GeekSpot, Top Ruby on Rails developers
email: office@geekspot.co
description: GeekSpot, Software House with Top Ruby on Rails developers.
 Web design and full stack development process of highly scalable web apps.
 CTO as a Service. Experienced Spree, ecommerce developers.
 Tech stack - Ruby on Rails, Heroku, Postgress, Javascript, React, Vue.js, Elixir and Phoenix framework.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://geekspot.co" # the base hostname & protocol for your site
twitter_username: charliestark
github_username:  charliestarkpl

# Build settings
markdown: kramdown

paginate: 8
paginate_path: "blog/page:num"
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sitemap:
    filename: "/sitemap.xml"
    exclude:
        - "/Gemfile"
        - "/Gemfile.lock"
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
